# platform = Red Hat Enterprise Linux 7
- name: "SSHD: Disable empty passwords"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^PermitEmptyPasswords"
    line="PermitEmptyPasswords no"
